%% PropSimWorking.m
% Plain-MATLAB time-stepping version of propulsion.slx.
%
% Pressure-loss model:
%   Oxidizer -> parallelOxPressureLoss
%   Fuel     -> branchPressureLoss
%
% Current assumption:
%   Darcy friction factor f = 0.04 for both oxidizer and fuel.
%   Therefore viscosity is NOT required for this version.

clear;
clc;
close all;


%% ---------------- Settings ----------------------------------------------

dt   = 0.01;     % [s]
tEnd = 10;       % [s]

% 'energy'    -> P_ox from internal energy + density
% 'saturated' -> P_ox from saturation pressure at T_ox
P_ox_model = 'energy';


%% ---------------- Constants / initial conditions ------------------------

T_amb      = 300;       % [K]
rho_f      = 794;       % [kg/m^3]
m_ox0      = 33.8916;   % [kg]
m_f0       = 9.678;     % [kg]

fric_power = 1;         % [W]
dP_fric    = 1;         % [Pa]


% Initial oxidizer volume
v_ox0 = m_ox0 / props( ...
    'D', ...
    'T', T_amb, ...
    'Q', 0, ...
    'N2O');


% Initial oxidizer mass / internal energy
m_ox_initial = v_ox0 * props( ...
    'D', ...
    'T', T_amb, ...
    'Q', 0, ...
    'N2O');

u_ox_initial = m_ox_initial * props( ...
    'U', ...
    'T', T_amb, ...
    'Q', 0, ...
    'N2O');


%% ---------------- Preallocate logs --------------------------------------

N = floor(tEnd / dt) + 1;

L.t        = zeros(1,N);
L.T_ox     = zeros(1,N);
L.P_ox     = zeros(1,N);
L.P_f      = zeros(1,N);

L.m_dot_ox = zeros(1,N);
L.m_dot_f  = zeros(1,N);

L.Pc       = zeros(1,N);
L.F        = zeros(1,N);
L.OF       = zeros(1,N);
L.Isp      = zeros(1,N);

L.m_ox     = zeros(1,N);
L.m_f      = zeros(1,N);


%% ---------------- States ------------------------------------------------

m_ox       = m_ox0;
m_f        = m_f0;

U_removed  = 0;
M_fuel_out = 0;


%% ---------------- Main loop ---------------------------------------------

nLogged = 0;

for k = 1:N

    t = (k - 1) * dt;

    try

        %% ---- Thermodynamic state ---------------------------------------

        v_ox = v_ox0 + M_fuel_out / rho_f;

        u_ox = u_ox_initial - U_removed;


        T_ox = props( ...
            'T', ...
            'D', m_ox / v_ox, ...
            'Q', 0, ...
            'N2O');


        rho_ox = props( ...
            'D', ...
            'T', T_ox, ...
            'Q', 0, ...
            'N2O');


        P_ox = calc_P_ox( ...
            P_ox_model, ...
            u_ox, ...
            v_ox, ...
            m_ox, ...
            T_ox);


        P_f = P_ox - dP_fric;


        % Fuel temperature is still required by the
        % energy-balance calculation below.
        T_f = props( ...
            'T', ...
            'D', rho_f, ...
            'P', P_f, ...
            'Ethanol');


        %% ---- Engine / feed-system solve --------------------------------

        [m_dot_ox, m_dot_f, Pc, F, OF, Isp] = ...
            engine_solver( ...
                P_ox, ...
                P_f, ...
                rho_ox, ...
                rho_f);


        %% ---- Energy-balance terms --------------------------------------

        w_piston = ...
            (m_dot_f / props( ...
                'D', ...
                'T', T_f, ...
                'P', P_f, ...
                'Ethanol')) ...
            * props( ...
                'P', ...
                'T', T_ox, ...
                'Q', 0, ...
                'N2O');


        u_out = ...
            m_dot_ox * props( ...
                'U', ...
                'T', T_ox, ...
                'Q', 0, ...
                'N2O');


    catch err

        warning( ...
            'Stopped at t = %.3f s: %s', ...
            t, ...
            err.message);

        break

    end


    %% ---- Log -----------------------------------------------------------

    nLogged = k;

    L.t(k)        = t;

    L.T_ox(k)     = T_ox;
    L.P_ox(k)     = P_ox;
    L.P_f(k)      = P_f;

    L.m_dot_ox(k) = m_dot_ox;
    L.m_dot_f(k)  = m_dot_f;

    L.Pc(k)       = Pc;
    L.F(k)        = F;
    L.OF(k)       = OF;
    L.Isp(k)      = Isp;

    L.m_ox(k)     = m_ox;
    L.m_f(k)      = m_f;


    %% ---- State update --------------------------------------------------

    U_removed = ...
        U_removed ...
        + dt * (w_piston + fric_power + u_out);


    M_fuel_out = ...
        M_fuel_out ...
        + dt * m_dot_f;


    m_ox = ...
        m_ox ...
        - dt * m_dot_ox;


    m_f = ...
        m_f ...
        - dt * m_dot_f;


    %% Stop if either tank empties

    if m_ox <= 0 || m_f <= 0

        warning( ...
            'A propellant tank emptied at t = %.3f s - stopping.', ...
            t + dt);

        break

    end

end


%% ---------------- Trim unused samples ----------------------------------

for fn = fieldnames(L)'

    L.(fn{1}) = ...
        L.(fn{1})(1:nLogged);

end


%% ---------------- Plots -------------------------------------------------

figure( ...
    'Name', 'Propulsion scopes', ...
    'Color', 'w', ...
    'Position', [100 100 1100 800]);


tl = tiledlayout( ...
    3, ...
    2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');


title( ...
    tl, ...
    'propulsion.slx - scope outputs');


scopePlot( ...
    tl, ...
    L.t, ...
    L.Pc / 1e6, ...
    'Chamber Pressure', ...
    'P_c [MPa]');


scopePlot( ...
    tl, ...
    L.t, ...
    L.F, ...
    'Thrust', ...
    'F [N]');


scopePlot( ...
    tl, ...
    L.t, ...
    L.OF, ...
    'Oxidizer Fuel Ratio', ...
    'O/F [-]');


scopePlot( ...
    tl, ...
    L.t, ...
    L.Isp, ...
    'Specific Impulse', ...
    'I_{sp} [s]');


scopePlot( ...
    tl, ...
    L.t, ...
    L.P_f / 1e6, ...
    'Scope (P_{fuel})', ...
    'P_{fuel} [MPa]');


scopePlot( ...
    tl, ...
    L.t, ...
    L.P_ox / 1e6, ...
    'Scope1 (P_{ox})', ...
    'P_{ox} [MPa]');


%% =======================================================================
%% Local functions
%% =======================================================================


function scopePlot(tl, t, y, ttl, ylab)

    nexttile(tl);

    plot( ...
        t, ...
        y, ...
        'LineWidth', ...
        1.5);

    grid on;

    title(ttl);

    xlabel('Time [s]');

    ylabel(ylab);

end


function y = props(varargin)

    % CoolProp wrapper
    y = double( ...
        py.CoolProp.CoolProp.PropsSI(varargin{:}));

end


function P_ox = calc_P_ox( ...
    model, ...
    u_ox, ...
    v_ox, ...
    m_ox, ...
    T_ox)


    switch model

        case 'energy'

            P_ox = props( ...
                'P', ...
                'Umass', u_ox / m_ox, ...
                'Dmass', m_ox / v_ox, ...
                'N2O');


        case 'saturated'

            P_ox = props( ...
                'P', ...
                'T', T_ox, ...
                'Q', 0, ...
                'N2O');


        otherwise

            error( ...
                'Unknown P_ox_model "%s".', ...
                model);

    end

end


function [m_dot_ox, m_dot_f, Pc, F, O_F, Isp] = ...
    engine_solver( ...
        P_ox, ...
        P_f, ...
        rho_ox, ...
        rho_f)


    %% Engine constants

    g0 = 9.81;               % [m/s^2]

    c_star = 2639.4;         % [m/s]

    A_t = 7.85398e-5;        % [m^2]

    A_e = 1.8816e-3;         % [m^2]

    C_f = A_e / A_t;         % retained from original model


    %% Initial guess
    % [mdot_ox; mdot_f; Pc]

    x0 = [ ...
        1.66337; ...
        0.478249; ...
        435.113 * 6894.76];


    %% fsolve options

    options = optimoptions( ...
        'fsolve', ...
        'Algorithm', 'levenberg-marquardt', ...
        'Display', 'off', ...
        'FunctionTolerance', 1e-6);


    %% Solve

    [x_sol, ~, exitflag] = fsolve( ...
        @(x) engine_residuals( ...
            x, ...
            P_ox, ...
            P_f, ...
            rho_ox, ...
            rho_f, ...
            A_t, ...
            c_star), ...
        x0, ...
        options);


    %% Fallback if solver fails

    if exitflag <= 0

        warning( ...
            'engine_solver:fsolve', ...
            ['fsolve did not converge. ' ...
             'Using initial guess for this timestep.']);

        x_sol = x0;

    end


    %% Outputs

    m_dot_ox = abs(x_sol(1));

    m_dot_f = abs(x_sol(2));

    Pc = abs(x_sol(3));


    m_dot_tot = ...
        m_dot_ox + m_dot_f;


    F = ...
        C_f * Pc * A_t;


    O_F = ...
        m_dot_ox / max(m_dot_f, 1e-6);


    Isp = ...
        F / ...
        (max(m_dot_tot, 1e-6) * g0);

end


function R = engine_residuals( ...
    x, ...
    P_ox, ...
    P_f, ...
    rho_ox, ...
    rho_f, ...
    A_t, ...
    c_star)


    %% Solver guesses

    m_dot_ox_guess = ...
        abs(x(1));

    m_dot_f_guess = ...
        abs(x(2));

    Pc_guess = ...
        abs(x(3));


    %% Vehicle geometry

    geom = vehicleGeometry();


    %% Current pressure-loss assumptions

    fFixed = 0.04;
    % Assumed Darcy friction factor


    roughness = 0;
    % Not used while fixed friction factor is supplied


    Cd = 1.0;
    % Matches the old injector equation for now


    dz = 0.9144;
    % [m] existing model value


    %% ---------------------------------------------------------------
    %% Oxidizer
    %% Two identical parallel branches
    %% ---------------------------------------------------------------

    ox = parallelOxPressureLoss( ...
        m_dot_ox_guess, ...
        rho_ox, ...
        NaN, ...                  % viscosity not needed
        geom.oxLeft.L, ...
        geom.oxLeft.D, ...
        roughness, ...
        10, ...                   % K
        9, ...                    % Cv
        Cd, ...
        2.20893e-5, ...           % total OX injector area [m^2]
        dz, ...
        fFixed=fFixed);


    dp_ox = ...
        ox.dP_total;


    %% ---------------------------------------------------------------
    %% Fuel
    %% One branch
    %% ---------------------------------------------------------------

    fuel = branchPressureLoss( ...
        m_dot_f_guess, ...
        rho_f, ...
        NaN, ...                  % viscosity not needed
        geom.fuel.L, ...
        geom.fuel.D, ...
        roughness, ...
        10, ...                   % K
        5.228, ...                % Cv
        Cd, ...
        1.8816e-3, ...            % injector area [m^2]
        dz, ...
        fFixed=fFixed);


    dp_f = ...
        fuel.dP_total;


    %% ---------------------------------------------------------------
    %% Residual equations
    %% ---------------------------------------------------------------

    R_ox = ...
        P_ox ...
        - dp_ox ...
        - Pc_guess;


    R_f = ...
        P_f ...
        - dp_f ...
        - Pc_guess;


    R_c = ...
        (m_dot_ox_guess + m_dot_f_guess) ...
        - (Pc_guess * A_t / c_star);


    R = [ ...
        R_ox; ...
        R_f; ...
        R_c];


    %% Protect fsolve from invalid values

    if any(~isfinite(R))

        R = [ ...
            1e6; ...
            1e6; ...
            1e6];

    end

end